[devices.relais-a]
description = "First Relais Card"
modbus-address = 1

[devices.relais-b]
description = "Dummy Relais Card"
modbus-address = 2

[coils.relay-1]
device = "relais-a"
address = 0
name = "relay1"
description = "A relais card"
default-status = "on"
tags = ["first-half"]

[coils.relay-2]
device = "relais-a"
address = 1
name = "relay2"
default-status = "on"
tags = ["first-half"]

[coils.relay-3]
device = "relais-a"
address = 2
name = "relay3"
default-status = "on"

[coils.relay-4]
device = "relais-a"
address = 3
name = "relay4"
default-status = "on"
